name: BEN10 Last Defense Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: pip install pygame pyinstaller numpy
        
      - name: Build with PyInstaller
        shell: bash
        run:
          DIR="Ben10 Last Defense (Antigravity Edition 2)"
          
          cd "$DIR"

          pyinstaller --windowed --name="BEN10_LastDefense" \
          --add-data "Anakotmai-Bold.ttf:." \
          --add-data "Anakotmai-Medium.ttf:." \
          --add-data "Finale.mp3:." \
          --add-data "b10mainmenu.mp3:." \
          --add-data "b10mainmenu.wav:." \
          --add-data "b10mainmenu_slow.wav:." \
          --add-data "ben10_defense:ben10_defense" \
          "main.py"
        
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BEN10-LastDefense-${{ matrix.os }}
          # ชี้ไปที่โฟลเดอร์ dist ที่อยู่ใน DIR
          path: "Ben10 Last Defense (Antigravity Edition 2)/dist/"
